<?php
$sites = [
	[
		'slug' => 'bhtal',
		'title' => 'BH Tal',
		'url' => 'https://versionindustries.com/work/client/bh-tal',
		'category' => 'Real Estate',
		'tags' => ['Wordpress','Custom Search','MLS'],
		'description' => '<p>Wordpress based real estate website. Properties managed by the client are seamlessly mixed in with those from a Multiple Listing Service.</p><p>Properties can be searched by any combination of attributes, including price, neighborhood, amenities, etc.</p>',
	],[
		'slug' => 'dahlen',
		'title' => 'Dahlen Studio',
		'url' => 'http://dahlenstudio.com/',
		'category' => 'Portfolio',
		'tags' => ['Zenphoto','Advanced Slideshows'],
		'description' => '<p></p>',
	],[
		'slug' => 'heroine',
		'title' => 'Heroine Boutique',
		'url' => 'http://heroine-boutique.myshopify.com/',
		'category' => 'Store',
		'tags' => ['Shopify'],
		'description' => '<p></p>',
	],[
		'slug' => 'hitched',
		'title' => 'Hitched Salon',
		'url' => 'http://hitchedsalon.com/',
		'category' => 'Store',
		'tags' => ['Wordpress'],
		'description' => '<p></p>',
	],[
		'slug' => 'jack',
		'title' => 'Jack Magazine',
		'url' => 'http://thejackmag.com/',
		'category' => 'Magazine',
		'tags' => ['Scrolling Layouts'],
		'description' => '<p></p>',
	],[
		'slug' => 'kaleidoscope',
		'title' => 'Kaleidoscope PR',
		'url' => 'https://versionindustries.com/work/client/kaleidoscope-consulting',
		'category' => 'Consulting',
		'tags' => ['Graphics Animations','Webcam'],
		'description' => '<p></p>',
	],[
		'slug' => 'nfa',
		'title' => 'Not Fade Away',
		'url' => 'https://versionindustries.com/work/client/not-fade-away',
		'category' => 'Film',
		'tags' => ['Image Animations','Music'],
		'description' => '<p></p>',
	],[
		'slug' => 'okay',
		'title' => 'Okay Africa',
		'url' => 'http://www.okayafrica.com/',
		'category' => 'News',
		'tags' => ['Wordpress'],
		'description' => '<p></p>',
	],[
		'slug' => 'trucking',
		'title' => 'Trucking Efficiency',
		'url' => 'https://versionindustries.com/work/client/trucking-efficiency',
		'category' => 'Corporate',
		'tags' => ['Drupal'],
		'description' => '<p></p>',
	],[
		'slug' => 'ventures',
		'title' => 'Ventures Africa',
		'url' => 'https://versionindustries.com/work/client/ventures-africa',
		'category' => 'News',
		'tags' => ['Wordpress','Article Organization'],
		'description' => '<p></p>',
	],
];
